name = "EddingtonInversion"
uuid = "6d05cea8-18e5-46a6-8a52-644cd40e080a"
authors = ["Gaétan Facchinetti <gaetanfacc@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
